### ISSUE TITLE
Setup workshop website

### ISSUE THREAD

**Issue by marcoow** [simplabs/progressive-web-apps-workshop#1]
based on this: https://mike.works/course/progressive-web-fundamentals-0d74af5

### TODO

- [x] add dates (26/27 April)
- [x] add location (London)
- [x] make the title bigger/nicer (I think the grey isn't super awesome and it could be a bit bigger)
- [x] fix google analytics tracking id (UA-53237918-21)

**Comment by trabaldini** [comment]
The grey title is part of the image I used. Do we have another image I can use?
The actual title is under the image.

**Comment by marcoow** [comment]
Can you crop the image so it doesn't include the title and add a pure text title? That's better anyway and we can then style it freely.

**Comment by marcoow** [comment]
I think you can actually just remove the header that's in the image as we have the one below anyway.
